# Generated by Django 5.0.14 on 2025-08-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_method_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='KES', max_length=3),
        ),
    ]
